# example better-issues config file

# On push to branch dev, patch version then create a tag with -dev suffix, 
# and create a label for that version
on_push_to:
  do: 
    this: 
      - version: patch dev
      - create: tag
      - create: label
    if: 
      - branch: test
# When a tag is created create a label for that tag
# on_tag:
#   do:
#     - create: 
#         what: label 
#         name: "{owner}:{tag}"
#         description: "some desciption"
#     - create: 
#         what: issue
#         title: Here goes a title
#         body: "Created new tag"
#         labels:
#           - bug
    
# periodically
# peridically:                          
#   each: 10d                            # Each 10 days do a series of actions
#   do: 
#     - check:                           # Perform a check before doing any action
#         tag:                           # Check all tags
#           matches: -dev$               # In this case we check all issues that have -dev suffix.
#           has_had_issues: false        # And if it has had no issues. 
#         then:                          # This will be run if it passes check      
#           - delete_tag: this  
#           - delete_label: this   
#           - version: update rc
#           - create: tag {version}
#           - create: label {version} 

    