on_push:                   
  - match:         
      branch: master
    do:
      - create:
          what: issue
          title: A test issue
          body: Asdasdaddasd as das dasdasdada **by** > @{payload.sender.login}
          labels: 
            - bug
            - duplicate