
# Available events
# on_push
# on_commit
# on_label
# on_create
# on_delete
# on_fork
# on_issue_comment
# on_issues
# on_pull_request

# Available Fiters
# branch
# commit
# ref
# owner
# 

# Available actions
# create
#   - label   <label_opts>
#   - issue   <issue_opts>
#   - tag     <tag_opts>
#   - release <release_opts>
# delete
#   - label   <label_opts>
#   - issue   <issue_opts>
#   - tag     <tag_opts>
#   - release <release_opts>
# edit
#   - label   <label_opts>
#   - issue   <issue_opts>
#   - tag     <tag_opts>
#   - release <release_opts>



# functions
# you can define a set of functions to remove duplication
# you can use them in "do" blocks
# ie: 
# on_push:
#   - branch: 
#     is: dev
#     do: 
#       - createTag 
#
# you can also pass arguments
# ie: 
# ...
# do: 
#   - createLabel:
#       name:  cool-label
#       color: ff2244 
# ...
#
defs: 
  # Function definition
  createTag:
    # Series of actions/commands
    # can have a single argument: 
    # - create: tag
    # or multiple arguments: 
    # - create: 
    #   what: tag
    #   name: test
    - create: tag
  createLabel:
    - create: label $1:$2
  release:
    - version: minor
    - release: 
        body: $1           # $1 = body | first argument (if is an array)
        name: <name>       # <x> anything inside <> will search for var
        tag_name: {latest} # {x} global variables
        draft: false
        prerelease: false
  
# vars
# you can also set some variables
# can be used anywhere by placing inside <>
# ie: <name>
vars: 
  name: test-project
  version: v0.0.1

# event
on_push:
  # check branch           
  - branch: 
      # is, checks if value is x              
      is: dev
      # do, does something if check passes
      do: 
        # createTag, wich will call defs.createTag defined above
        - createTag 
        # createLabel, will call defs.createLabel with a set of args
        - createLabel:
            - "{owner}"
            - "{tag}"

  # check owner           
  - owner: 
      # check if owner is "nombrekeff"            
      is: nombrekeff
      do: 
        - createLabel:
            - "{owner}"

# Event can omit filter
on_issue:
  do: 
    - addComment:
        - body: Hey, thanks for reporting, we will be adding it soon!
    - addLabel:
        - name: topic:events


on_issue:
  # check branch           
  - if: owner: is: nombrekeff
    do: 
      - addLabel:
          name: keffs 